const main = {
  red: {
    a: {
      color: "red",
      row: 1,
      num: "2",
      prev: null,
      id: 1,
      selected: false,
      disabled: false,
    },
    b: {
      color: "red",
      row: 1,
      num: "3",
      prev: 1,
      id: 2,
      selected: false,
      disabled: false,
    },
    c: {
      color: "red",
      row: 1,
      num: "4",
      prev: 2,
      id: 3,
      selected: false,
      disabled: false,
    },
    d: {
      color: "red",
      row: 1,
      num: "5",
      prev: 3,
      id: 4,
      selected: false,
      disabled: false,
    },
    e: {
      color: "red",
      row: 1,
      num: "6",
      prev: 4,
      id: 5,
      selected: false,
      disabled: false,
    },
    f: {
      color: "red",
      row: 1,
      num: "7",
      prev: 5,
      id: 6,
      selected: false,
      disabled: false,
    },
    g: {
      color: "red",
      row: 1,
      num: "8",
      prev: 6,
      id: 7,
      selected: false,
      disabled: false,
    },
    h: {
      color: "red",
      row: 1,
      num: "9",
      prev: 7,
      id: 8,
      selected: false,
      disabled: false,
    },
    i: {
      color: "red",
      row: 1,
      num: "10",
      prev: 8,
      id: 9,
      selected: false,
      disabled: false,
    },
    j: {
      color: "red",
      row: 1,
      num: "11",
      prev: 9,
      id: 10,
      selected: false,
      disabled: false,
    },
    k: {
      color: "red",
      row: 1,
      num: "12",
      prev: 10,
      id: 11,
      selected: false,
      disabled: false,
    },
    l: {
      color: "red",
      row: 1,
      num: "lock",
      prev: 11,
      id: 12,
      selected: false,
      disabled: false,
    },
  },
  yellow: {
    a: {
      color: "yellow",
      row: 1,
      num: "2",
      prev: null,
      id: 1,
      selected: false,
      disabled: false,
    },
    b: {
      color: "yellow",
      row: 1,
      num: "3",
      prev: 1,
      id: 2,
      selected: false,
      disabled: false,
    },
    c: {
      color: "yellow",
      row: 1,
      num: "4",
      prev: 2,
      id: 3,
      selected: false,
      disabled: false,
    },
    d: {
      color: "yellow",
      row: 1,
      num: "5",
      prev: 3,
      id: 4,
      selected: false,
      disabled: false,
    },
    e: {
      color: "yellow",
      row: 1,
      num: "6",
      prev: 4,
      id: 5,
      selected: false,
      disabled: false,
    },
    f: {
      color: "yellow",
      row: 1,
      num: "7",
      prev: 5,
      id: 6,
      selected: false,
      disabled: false,
    },
    g: {
      color: "yellow",
      row: 1,
      num: "8",
      prev: 6,
      id: 7,
      selected: false,
      disabled: false,
    },
    h: {
      color: "yellow",
      row: 1,
      num: "9",
      prev: 7,
      id: 8,
      selected: false,
      disabled: false,
    },
    i: {
      color: "yellow",
      row: 1,
      num: "10",
      prev: 8,
      id: 9,
      selected: false,
      disabled: false,
    },
    j: {
      color: "yellow",
      row: 1,
      num: "11",
      prev: 9,
      id: 10,
      selected: false,
      disabled: false,
    },
    k: {
      color: "yellow",
      row: 1,
      num: "12",
      prev: 10,
      id: 11,
      selected: false,
      disabled: false,
    },
    l: {
      color: "yellow",
      row: 1,
      num: "lock",
      prev: 11,
      id: 12,
      selected: false,
      disabled: false,
    },
  },
  green: {
    a: {
      color: "green",
      row: 1,
      num: "12",
      prev: null,
      id: 1,
      selected: false,
      disabled: false,
    },
    b: {
      color: "green",
      row: 1,
      num: "11",
      prev: 1,
      id: 2,
      selected: false,
      disabled: false,
    },
    c: {
      color: "green",
      row: 1,
      num: "10",
      prev: 2,
      id: 3,
      selected: false,
      disabled: false,
    },
    d: {
      color: "green",
      row: 1,
      num: "9",
      prev: 3,
      id: 4,
      selected: false,
      disabled: false,
    },
    e: {
      color: "green",
      row: 1,
      num: "8",
      prev: 4,
      id: 5,
      selected: false,
      disabled: false,
    },
    f: {
      color: "green",
      row: 1,
      num: "7",
      prev: 5,
      id: 6,
      selected: false,
      disabled: false,
    },
    g: {
      color: "green",
      row: 1,
      num: "6",
      prev: 6,
      id: 7,
      selected: false,
      disabled: false,
    },
    h: {
      color: "green",
      row: 1,
      num: "5",
      prev: 7,
      id: 8,
      selected: false,
      disabled: false,
    },
    i: {
      color: "green",
      row: 1,
      num: "4",
      prev: 8,
      id: 9,
      selected: false,
      disabled: false,
    },
    j: {
      color: "green",
      row: 1,
      num: "3",
      prev: 9,
      id: 10,
      selected: false,
      disabled: false,
    },
    k: {
      color: "green",
      row: 1,
      num: "2",
      prev: 10,
      id: 11,
      selected: false,
      disabled: false,
    },
    l: {
      color: "green",
      row: 1,
      num: "lock",
      prev: 11,
      id: 12,
      selected: false,
      disabled: false,
    },
  },
  blue: {
    a: {
      color: "blue",
      row: 1,
      num: "12",
      prev: null,
      id: 1,
      selected: false,
      disabled: false,
    },
    b: {
      color: "blue",
      row: 1,
      num: "11",
      prev: 1,
      id: 2,
      selected: false,
      disabled: false,
    },
    c: {
      color: "blue",
      row: 1,
      num: "10",
      prev: 2,
      id: 3,
      selected: false,
      disabled: false,
    },
    d: {
      color: "blue",
      row: 1,
      num: "9",
      prev: 3,
      id: 4,
      selected: false,
      disabled: false,
    },
    e: {
      color: "blue",
      row: 1,
      num: "8",
      prev: 4,
      id: 5,
      selected: false,
      disabled: false,
    },
    f: {
      color: "blue",
      row: 1,
      num: "7",
      prev: 5,
      id: 6,
      selected: false,
      disabled: false,
    },
    g: {
      color: "blue",
      row: 1,
      num: "6",
      prev: 6,
      id: 7,
      selected: false,
      disabled: false,
    },
    h: {
      color: "blue",
      row: 1,
      num: "5",
      prev: 7,
      id: 8,
      selected: false,
      disabled: false,
    },
    i: {
      color: "blue",
      row: 1,
      num: "4",
      prev: 8,
      id: 9,
      selected: false,
      disabled: false,
    },
    j: {
      color: "blue",
      row: 1,
      num: "3",
      prev: 9,
      id: 10,
      selected: false,
      disabled: false,
    },
    k: {
      color: "blue",
      row: 1,
      num: "2",
      prev: 10,
      id: 11,
      selected: false,
      disabled: false,
    },
    l: {
      color: "blue",
      row: 1,
      num: "lock",
      prev: 11,
      id: 12,
      selected: false,
      disabled: false,
    },
  },
  negatives: {
    first: false,
    second: false,
    third: false,
    fourth: false,
  },
};

const switchedNumbers = {
  red: {
    a: {
      color: "red",
      row: 1,
      num: "10",
      prev: null,
      id: 1,
      selected: false,
      disabled: false,
    },
    b: {
      color: "red",
      row: 1,
      num: "6",
      prev: 1,
      id: 2,
      selected: false,
      disabled: false,
    },
    c: {
      color: "red",
      row: 1,
      num: "2",
      prev: 2,
      id: 3,
      selected: false,
      disabled: false,
    },
    d: {
      color: "red",
      row: 1,
      num: "8",
      prev: 3,
      id: 4,
      selected: false,
      disabled: false,
    },
    e: {
      color: "red",
      row: 1,
      num: "3",
      prev: 4,
      id: 5,
      selected: false,
      disabled: false,
    },
    f: {
      color: "red",
      row: 1,
      num: "4",
      prev: 5,
      id: 6,
      selected: false,
      disabled: false,
    },
    g: {
      color: "red",
      row: 1,
      num: "12",
      prev: 6,
      id: 7,
      selected: false,
      disabled: false,
    },
    h: {
      color: "red",
      row: 1,
      num: "5",
      prev: 7,
      id: 8,
      selected: false,
      disabled: false,
    },
    i: {
      color: "red",
      row: 1,
      num: "9",
      prev: 8,
      id: 9,
      selected: false,
      disabled: false,
    },
    j: {
      color: "red",
      row: 1,
      num: "7",
      prev: 9,
      id: 10,
      selected: false,
      disabled: false,
    },
    k: {
      color: "red",
      row: 1,
      num: "11",
      prev: 10,
      id: 11,
      selected: false,
      disabled: false,
    },
    l: {
      color: "red",
      row: 1,
      num: "lock",
      prev: 11,
      id: 12,
      selected: false,
      disabled: false,
    },
  },
  yellow: {
    a: {
      color: "yellow",
      row: 1,
      num: "9",
      prev: null,
      id: 1,
      selected: false,
      disabled: false,
    },
    b: {
      color: "yellow",
      row: 1,
      num: "12",
      prev: 1,
      id: 2,
      selected: false,
      disabled: false,
    },
    c: {
      color: "yellow",
      row: 1,
      num: "4",
      prev: 2,
      id: 3,
      selected: false,
      disabled: false,
    },
    d: {
      color: "yellow",
      row: 1,
      num: "6",
      prev: 3,
      id: 4,
      selected: false,
      disabled: false,
    },
    e: {
      color: "yellow",
      row: 1,
      num: "7",
      prev: 4,
      id: 5,
      selected: false,
      disabled: false,
    },
    f: {
      color: "yellow",
      row: 1,
      num: "2",
      prev: 5,
      id: 6,
      selected: false,
      disabled: false,
    },
    g: {
      color: "yellow",
      row: 1,
      num: "5",
      prev: 6,
      id: 7,
      selected: false,
      disabled: false,
    },
    h: {
      color: "yellow",
      row: 1,
      num: "8",
      prev: 7,
      id: 8,
      selected: false,
      disabled: false,
    },
    i: {
      color: "yellow",
      row: 1,
      num: "11",
      prev: 8,
      id: 9,
      selected: false,
      disabled: false,
    },
    j: {
      color: "yellow",
      row: 1,
      num: "3",
      prev: 9,
      id: 10,
      selected: false,
      disabled: false,
    },
    k: {
      color: "yellow",
      row: 1,
      num: "10",
      prev: 10,
      id: 11,
      selected: false,
      disabled: false,
    },
    l: {
      color: "yellow",
      row: 1,
      num: "lock",
      prev: 11,
      id: 12,
      selected: false,
      disabled: false,
    },
  },
  green: {
    a: {
      color: "green",
      row: 1,
      num: "8",
      prev: null,
      id: 1,
      selected: false,
      disabled: false,
    },
    b: {
      color: "green",
      row: 1,
      num: "2",
      prev: 1,
      id: 2,
      selected: false,
      disabled: false,
    },
    c: {
      color: "green",
      row: 1,
      num: "10",
      prev: 2,
      id: 3,
      selected: false,
      disabled: false,
    },
    d: {
      color: "green",
      row: 1,
      num: "12",
      prev: 3,
      id: 4,
      selected: false,
      disabled: false,
    },
    e: {
      color: "green",
      row: 1,
      num: "6",
      prev: 4,
      id: 5,
      selected: false,
      disabled: false,
    },
    f: {
      color: "green",
      row: 1,
      num: "9",
      prev: 5,
      id: 6,
      selected: false,
      disabled: false,
    },
    g: {
      color: "green",
      row: 1,
      num: "7",
      prev: 6,
      id: 7,
      selected: false,
      disabled: false,
    },
    h: {
      color: "green",
      row: 1,
      num: "4",
      prev: 7,
      id: 8,
      selected: false,
      disabled: false,
    },
    i: {
      color: "green",
      row: 1,
      num: "5",
      prev: 8,
      id: 9,
      selected: false,
      disabled: false,
    },
    j: {
      color: "green",
      row: 1,
      num: "11",
      prev: 9,
      id: 10,
      selected: false,
      disabled: false,
    },
    k: {
      color: "green",
      row: 1,
      num: "3",
      prev: 10,
      id: 11,
      selected: false,
      disabled: false,
    },
    l: {
      color: "green",
      row: 1,
      num: "lock",
      prev: 11,
      id: 12,
      selected: false,
      disabled: false,
    },
  },
  blue: {
    a: {
      color: "blue",
      row: 1,
      num: "5",
      prev: null,
      id: 1,
      selected: false,
      disabled: false,
    },
    b: {
      color: "blue",
      row: 1,
      num: "7",
      prev: 1,
      id: 2,
      selected: false,
      disabled: false,
    },
    c: {
      color: "blue",
      row: 1,
      num: "11",
      prev: 2,
      id: 3,
      selected: false,
      disabled: false,
    },
    d: {
      color: "blue",
      row: 1,
      num: "9",
      prev: 3,
      id: 4,
      selected: false,
      disabled: false,
    },
    e: {
      color: "blue",
      row: 1,
      num: "12",
      prev: 4,
      id: 5,
      selected: false,
      disabled: false,
    },
    f: {
      color: "blue",
      row: 1,
      num: "3",
      prev: 5,
      id: 6,
      selected: false,
      disabled: false,
    },
    g: {
      color: "blue",
      row: 1,
      num: "8",
      prev: 6,
      id: 7,
      selected: false,
      disabled: false,
    },
    h: {
      color: "blue",
      row: 1,
      num: "10",
      prev: 7,
      id: 8,
      selected: false,
      disabled: false,
    },
    i: {
      color: "blue",
      row: 1,
      num: "2",
      prev: 8,
      id: 9,
      selected: false,
      disabled: false,
    },
    j: {
      color: "blue",
      row: 1,
      num: "6",
      prev: 9,
      id: 10,
      selected: false,
      disabled: false,
    },
    k: {
      color: "blue",
      row: 1,
      num: "4",
      prev: 10,
      id: 11,
      selected: false,
      disabled: false,
    },
    l: {
      color: "blue",
      row: 1,
      num: "lock",
      prev: 11,
      id: 12,
      selected: false,
      disabled: false,
    },
  },
  negatives: {
    first: false,
    second: false,
    third: false,
    fourth: false,
  },
};

const switchedColors = {
  red: {
    a: {
      color: "yellow",
      row: 1,
      num: "2",
      prev: null,
      id: 1,
      selected: false,
      disabled: false,
    },
    b: {
      color: "yellow",
      row: 1,
      num: "3",
      prev: 1,
      id: 2,
      selected: false,
      disabled: false,
    },
    c: {
      color: "yellow",
      row: 1,
      num: "4",
      prev: 2,
      id: 3,
      selected: false,
      disabled: false,
    },
    d: {
      color: "blue",
      row: 1,
      num: "5",
      prev: 3,
      id: 4,
      selected: false,
      disabled: false,
    },
    e: {
      color: "blue",
      row: 1,
      num: "6",
      prev: 4,
      id: 5,
      selected: false,
      disabled: false,
    },
    f: {
      color: "blue",
      row: 1,
      num: "7",
      prev: 5,
      id: 6,
      selected: false,
      disabled: false,
    },
    g: {
      color: "green",
      row: 1,
      num: "8",
      prev: 6,
      id: 7,
      selected: false,
      disabled: false,
    },
    h: {
      color: "green",
      row: 1,
      num: "9",
      prev: 7,
      id: 8,
      selected: false,
      disabled: false,
    },
    i: {
      color: "green",
      row: 1,
      num: "10",
      prev: 8,
      id: 9,
      selected: false,
      disabled: false,
    },
    j: {
      color: "red",
      row: 1,
      num: "11",
      prev: 9,
      id: 10,
      selected: false,
      disabled: false,
    },
    k: {
      color: "red",
      row: 1,
      num: "12",
      prev: 10,
      id: 11,
      selected: false,
      disabled: false,
    },
    l: {
      color: "red",
      row: 1,
      num: "lock",
      prev: 11,
      id: 12,
      selected: false,
      disabled: false,
    },
  },
  yellow: {
    a: {
      color: "red",
      row: 1,
      num: "2",
      prev: null,
      id: 1,
      selected: false,
      disabled: false,
    },
    b: {
      color: "red",
      row: 1,
      num: "3",
      prev: 1,
      id: 2,
      selected: false,
      disabled: false,
    },
    c: {
      color: "green",
      row: 1,
      num: "4",
      prev: 2,
      id: 3,
      selected: false,
      disabled: false,
    },
    d: {
      color: "green",
      row: 1,
      num: "5",
      prev: 3,
      id: 4,
      selected: false,
      disabled: false,
    },
    e: {
      color: "green",
      row: 1,
      num: "6",
      prev: 4,
      id: 5,
      selected: false,
      disabled: false,
    },
    f: {
      color: "green",
      row: 1,
      num: "7",
      prev: 5,
      id: 6,
      selected: false,
      disabled: false,
    },
    g: {
      color: "blue",
      row: 1,
      num: "8",
      prev: 6,
      id: 7,
      selected: false,
      disabled: false,
    },
    h: {
      color: "blue",
      row: 1,
      num: "9",
      prev: 7,
      id: 8,
      selected: false,
      disabled: false,
    },
    i: {
      color: "yellow",
      row: 1,
      num: "10",
      prev: 8,
      id: 9,
      selected: false,
      disabled: false,
    },
    j: {
      color: "yellow",
      row: 1,
      num: "11",
      prev: 9,
      id: 10,
      selected: false,
      disabled: false,
    },
    k: {
      color: "yellow",
      row: 1,
      num: "12",
      prev: 10,
      id: 11,
      selected: false,
      disabled: false,
    },
    l: {
      color: "yellow",
      row: 1,
      num: "lock",
      prev: 11,
      id: 12,
      selected: false,
      disabled: false,
    },
  },
  green: {
    a: {
      color: "blue",
      row: 1,
      num: "12",
      prev: null,
      id: 1,
      selected: false,
      disabled: false,
    },
    b: {
      color: "blue",
      row: 1,
      num: "11",
      prev: 1,
      id: 2,
      selected: false,
      disabled: false,
    },
    c: {
      color: "blue",
      row: 1,
      num: "10",
      prev: 2,
      id: 3,
      selected: false,
      disabled: false,
    },
    d: {
      color: "yellow",
      row: 1,
      num: "9",
      prev: 3,
      id: 4,
      selected: false,
      disabled: false,
    },
    e: {
      color: "yellow",
      row: 1,
      num: "8",
      prev: 4,
      id: 5,
      selected: false,
      disabled: false,
    },
    f: {
      color: "yellow",
      row: 1,
      num: "7",
      prev: 5,
      id: 6,
      selected: false,
      disabled: false,
    },
    g: {
      color: "red",
      row: 1,
      num: "6",
      prev: 6,
      id: 7,
      selected: false,
      disabled: false,
    },
    h: {
      color: "red",
      row: 1,
      num: "5",
      prev: 7,
      id: 8,
      selected: false,
      disabled: false,
    },
    i: {
      color: "red",
      row: 1,
      num: "4",
      prev: 8,
      id: 9,
      selected: false,
      disabled: false,
    },
    j: {
      color: "green",
      row: 1,
      num: "3",
      prev: 9,
      id: 10,
      selected: false,
      disabled: false,
    },
    k: {
      color: "green",
      row: 1,
      num: "2",
      prev: 10,
      id: 11,
      selected: false,
      disabled: false,
    },
    l: {
      color: "green",
      row: 1,
      num: "lock",
      prev: 11,
      id: 12,
      selected: false,
      disabled: false,
    },
  },
  blue: {
    a: {
      color: "green",
      row: 1,
      num: "12",
      prev: null,
      id: 1,
      selected: false,
      disabled: false,
    },
    b: {
      color: "green",
      row: 1,
      num: "11",
      prev: 1,
      id: 2,
      selected: false,
      disabled: false,
    },
    c: {
      color: "red",
      row: 1,
      num: "10",
      prev: 2,
      id: 3,
      selected: false,
      disabled: false,
    },
    d: {
      color: "red",
      row: 1,
      num: "9",
      prev: 3,
      id: 4,
      selected: false,
      disabled: false,
    },
    e: {
      color: "red",
      row: 1,
      num: "8",
      prev: 4,
      id: 5,
      selected: false,
      disabled: false,
    },
    f: {
      color: "red",
      row: 1,
      num: "7",
      prev: 5,
      id: 6,
      selected: false,
      disabled: false,
    },
    g: {
      color: "yellow",
      row: 1,
      num: "6",
      prev: 6,
      id: 7,
      selected: false,
      disabled: false,
    },
    h: {
      color: "yellow",
      row: 1,
      num: "5",
      prev: 7,
      id: 8,
      selected: false,
      disabled: false,
    },
    i: {
      color: "blue",
      row: 1,
      num: "4",
      prev: 8,
      id: 9,
      selected: false,
      disabled: false,
    },
    j: {
      color: "blue",
      row: 1,
      num: "3",
      prev: 9,
      id: 10,
      selected: false,
      disabled: false,
    },
    k: {
      color: "blue",
      row: 1,
      num: "2",
      prev: 10,
      id: 11,
      selected: false,
      disabled: false,
    },
    l: {
      color: "blue",
      row: 1,
      num: "lock",
      prev: 11,
      id: 12,
      selected: false,
      disabled: false,
    },
  },
  negatives: {
    first: false,
    second: false,
    third: false,
    fourth: false,
  },
};

export const games = {
  main: main,
  switchedColors: switchedColors,
  switchedNumbers: switchedNumbers,
};
