import react, { useEffect, useState } from "react";
import { type NextPage } from "next";
import Head from "next/head";

import {
  RocketLaunchIcon,
  LockOpenIcon,
  LockClosedIcon,
} from "@heroicons/react/24/solid";

import NumberBox from "../../components/quixx/NumberBox";
import { main } from "../../components/quixx/games";

const Home: NextPage = () => {
  const [marker, setMarker] = useState(
    <RocketLaunchIcon className="text-cyan-500" />
  );
  const [selected, setSelected] = useState<number[]>([])
  const [disabled, setDisabled] = useState<number[]>([])
  const [gameInfo, setGameInfo] = useState(main);

  useEffect(() => {
    const tempInfo = gameInfo.map((item) => {
      if (selected.includes(item.id)) {
        return {...item, selected: true, disabled: false}
      } else {
        return {...item, selected: false}
      }
    })
    setGameInfo(tempInfo)
  }, [selected])


  const handleBoxClick = (id: number) => {
    const tempSelected = selected.includes(id) ? selected.filter(item => item !== id) : [...selected, id]
    setSelected(tempSelected)
    console.log(selected)
  };

  return (
    <>
      <Head>
        <title>Zeth | Quixx</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-gradient-to-b from-cyan-600 to-purple-800">
        <div className="my-auto mx-auto w-3/4 min-w-[800px] rounded bg-white/10 p-5">
          <div className="grid w-full grid-cols-12 gap-1 overflow-x-auto rounded bg-white/80 p-5">
            {gameInfo.map((item) => (
              <NumberBox
                disabled={item.disabled}
                key={item.id}
                color={item.color}
                number={item.num}
                selected={item.selected}
                icon={marker}
                onClick={() => handleBoxClick(item.id)}
              />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
5;
