import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-cyan-600 to-purple-800">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight sm:text-[5rem]">
            <span className="text-cyan-300">Zeth</span> <span className="text-purple-300">Porter</span>
          </h1>
          <div className="container max-w-xs rounded-xl bg-white/10 p-4 text-white">
            This is still under development. Check out some other stuff I&apos;ve made below.
          </div>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-1 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="/quixx"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Quixx</h3>
              <div className="text-lg">
                online free to use card for the dice game Quixx
              </div>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
